server {
    listen 80;
    server_name _;

    root /srv/ftp;
    index index.html;

    autoindex on;
    autoindex_exact_size off;
    autoindex_localtime on;

    location / {
        try_files $uri $uri/ =404;
    }
}
